/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.paneles;

import vista.Bitacora;
import controlador.ctrMenuAlterno;
/**
 *
 * @author RojeruSan
 */
public class pnlFeeBack extends javax.swing.JPanel {
ctrMenuAlterno c;
    /**
     * Creates new form pnlHome
     */
    public pnlFeeBack() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMenu2 = new javax.swing.JPanel();
        btn162 = new rsbuttom.RSButtonMetro();
        btn17 = new rsbuttom.RSButtonMetro();
        btn18 = new rsbuttom.RSButtonMetro();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        pnlMenu2.setBackground(new java.awt.Color(239, 238, 244));
        pnlMenu2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 5, 0, 0, new java.awt.Color(239, 238, 244)));

        btn162.setBackground(new java.awt.Color(239, 238, 244));
        btn162.setForeground(new java.awt.Color(128, 128, 131));
        btn162.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
        btn162.setText("Bitacora");
        btn162.setColorHover(new java.awt.Color(204, 204, 204));
        btn162.setColorNormal(new java.awt.Color(239, 238, 244));
        btn162.setColorPressed(new java.awt.Color(204, 204, 204));
        btn162.setColorTextHover(new java.awt.Color(128, 128, 131));
        btn162.setColorTextNormal(new java.awt.Color(128, 128, 131));
        btn162.setColorTextPressed(new java.awt.Color(128, 128, 131));
        btn162.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn162.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn162.setIconTextGap(19);
        btn162.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn162MousePressed(evt);
            }
        });
        btn162.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn162ActionPerformed(evt);
            }
        });

        btn17.setBackground(new java.awt.Color(239, 238, 244));
        btn17.setForeground(new java.awt.Color(128, 128, 131));
        btn17.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
        btn17.setText("Perfil");
        btn17.setColorHover(new java.awt.Color(204, 204, 204));
        btn17.setColorNormal(new java.awt.Color(239, 238, 244));
        btn17.setColorPressed(new java.awt.Color(204, 204, 204));
        btn17.setColorTextHover(new java.awt.Color(128, 128, 131));
        btn17.setColorTextNormal(new java.awt.Color(128, 128, 131));
        btn17.setColorTextPressed(new java.awt.Color(128, 128, 131));
        btn17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn17.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn17.setIconTextGap(19);
        btn17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn17MousePressed(evt);
            }
        });
        btn17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn17ActionPerformed(evt);
            }
        });

        btn18.setBackground(new java.awt.Color(239, 238, 244));
        btn18.setForeground(new java.awt.Color(128, 128, 131));
        btn18.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
        btn18.setText("Respaldar y Restaurar");
        btn18.setColorHover(new java.awt.Color(204, 204, 204));
        btn18.setColorNormal(new java.awt.Color(239, 238, 244));
        btn18.setColorPressed(new java.awt.Color(204, 204, 204));
        btn18.setColorTextHover(new java.awt.Color(128, 128, 131));
        btn18.setColorTextNormal(new java.awt.Color(128, 128, 131));
        btn18.setColorTextPressed(new java.awt.Color(128, 128, 131));
        btn18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn18.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn18.setIconTextGap(19);
        btn18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn18MousePressed(evt);
            }
        });
        btn18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn18ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMenu2Layout = new javax.swing.GroupLayout(pnlMenu2);
        pnlMenu2.setLayout(pnlMenu2Layout);
        pnlMenu2Layout.setHorizontalGroup(
            pnlMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn162, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
            .addComponent(btn17, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
            .addComponent(btn18, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
        );
        pnlMenu2Layout.setVerticalGroup(
            pnlMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenu2Layout.createSequentialGroup()
                .addComponent(btn162, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn17, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn18, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        c=new controlador.ctrMenuAlterno(this);
        btn162.addActionListener(c);
        c=new controlador.ctrMenuAlterno(this);
        btn17.addActionListener(c);
        c=new controlador.ctrMenuAlterno(this);
        btn18.addActionListener(c);

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(128, 128, 131));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/0Logo1listo.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pnlMenu2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(746, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(150, 150, 150)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 685, Short.MAX_VALUE)
                    .addGap(151, 151, 151)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(236, Short.MAX_VALUE)
                .addComponent(pnlMenu2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(216, 216, 216))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn162MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn162MousePressed
       
    }//GEN-LAST:event_btn162MousePressed

    private void btn162ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn162ActionPerformed

    }//GEN-LAST:event_btn162ActionPerformed

    private void btn17MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn17MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn17MousePressed

    private void btn17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn17ActionPerformed

    private void btn18MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn18MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn18MousePressed

    private void btn18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn18ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public rsbuttom.RSButtonMetro btn162;
    public rsbuttom.RSButtonMetro btn17;
    public rsbuttom.RSButtonMetro btn18;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel pnlMenu2;
    // End of variables declaration//GEN-END:variables
}
